Sprint 11
shooin13/Image_Feed pull request #2
Opened 2024-11-04 19:15 UTC by shooin13

2024-11-05 09:17 UTC, Kirchberg requested changes
⚠️ Критические замечания (это нужно исправить обязательно):

1. В проекте в двух местах используется `implicit unwrap`, который можно обработать и выдать ошибку пользователю. В файле `OAuth2Service` при формировании `url` явно указываем !. В файле `Constants` у `defaultBaseURL` также указываем !. Два `implicit unwrap` можно избежать если в местах использования безопасно извлекать значение при помощи `guard let`, `if let` и т.д. Необходимо поправить в соответствии с пунктом задания 2.
2. При входе пользователя в профиль не обновляются лейблы на экране `ProfileViewController`, [[см. скриншот](https://ibb.co/NWS5fTL)](https://ibb.co/NWS5fTL). Необходимо поправить в соответствии с пунктом задания 5.
3. Необходимо придерживаться в соответствии с пунктом задания 10 конкретного формата строк, поменять с «Ошибка» на «Что-то пошло не так(», «Не удалось получить токен:» на «Не удалось войти в систему»

Без исправлений этих пунктов, я не смогу принять у тебя работу. Если возникнут вопросы, обязательно задавай их Наставнику!

2024-11-05 09:17 UTC, Kirchberg commented on ImageFeedThird/AppDelegate.swift
> +  }()
Было бы хорошо эту переменную не хранить в AppDelegate, а вынести в enum Constants, поскольку при использовании его вне файла AppDelegate нам необходимо будет делать UIApplication.shared.delegate as? AppDelegate, а операция as? является трудозатратной по производительности, ее рекомендуется использовать в редких случаях, так как она просаживает производительность

2024-11-05 09:17 UTC, Kirchberg commented on ImageFeedThird/Assets.xcassets/placeholder.imageset/placeholder.jpeg
Было бы хорошо использовать этот плейсхолдер, так как при не заполнении используется твоя фотография как моковая :)

2024-11-05 09:17 UTC, Kirchberg commented on ImageFeedThird/Services/OAuth2Service.swift
> +    }
🔥

2024-11-05 09:17 UTC, Kirchberg commented on ImageFeedThird/TabBarController/Profile/ProfileViewController.swift
> +  }
Функция не используется, хотя должна

2024-11-05 09:17 UTC, Kirchberg commented on ImageFeedThird/Models/ProfileResult.swift
Для улучшения структуры `ProfileResult`, можно внести несколько изменений, чтобы код был более читаемым и удобным для работы. Например, можно использовать `CodingKeys`, чтобы управлять названиями полей, а также добавить свойства, используя `CamelCase` вместо `snake_case`:

```swift
import Foundation

// MARK: - ProfileResult

struct ProfileResult: Decodable {
    let id: String
    let username: String
    let firstName: String
    let lastName: String
    let bio: String?
    
    private enum CodingKeys: String, CodingKey {
        case id
        case username
        case firstName = "first_name"
        case lastName = "last_name"
        case bio
    }
}
```

2024-11-06 20:47 UTC, shooin13 commented on ImageFeedThird/AppDelegate.swift
> +  }()
Спасибо, переместил в AppDelegate

2024-11-06 20:47 UTC, shooin13 commented on ImageFeedThird/Assets.xcassets/placeholder.imageset/placeholder.jpeg
Сделано)

2024-11-06 20:48 UTC, shooin13 commented on ImageFeedThird/TabBarController/Profile/ProfileViewController.swift
> +  }
Видимо я писал ее когда было поздно)))
Добавил в viewDidLoad))

2024-11-06 21:04 UTC, shooin13 commented
@Kirchberg 

Из критических поправил первые два замечания, по третьему - придется весь спринт перелопатить заново :(
Специально писал алерты для себя

2024-11-07 17:43 UTC, Kirchberg commented
> @Kirchberg
> 
> Из критических поправил первые два замечания, по третьему - придется весь спринт перелопатить заново :( Специально писал алерты для себя

Привет, но там нужно только поменять строки с одних на других, ничего дополнительного делать не нужно, что ты имел в виду?

2024-11-07 17:45 UTC, shooin13 commented
@Kirchberg да, я понимаю, просто не помню в каких случаях какие слова Яндекс просит писать))
Не вопрос - посмотрю все, поменяю)

2024-11-07 17:46 UTC, Kirchberg commented on ImageFeedThird/Auth/SplashViewController.swift
> +        self.presentErrorAlert(message: "Failed to load profile")
В данном случае как раз можно передавать строку «Не удалось войти в систему», сейчас с точки зрения пользователя у нас строки, то на русском языке, то на английском. В реальном продакшн коде пользователь бы не понял почему так.

Если возникнут вопросы, обязательно задавай их Наставнику, он поможет тебе в решении сложных вопросов

2024-11-24 07:32 UTC, Kirchberg commented
При попытке получить профиль происходит ошибка декодирования, так как не все данные могут быть корректно обработаны. В структуре `ProfileResult` указан `lastName` типа `String`, хотя он может не прийти вовсе, то есть необходимо поменять тип на `String?`. Текст ошибки: `[objectTask]: Ошибка декодирования The data couldn’t be read because it is missing., Данные: {"id":"7otKKchRTAk","updated_at":"2024-11-24T07:25:14Z","username":"ypios","name":"Yandex","first_name":"Yandex","last_name":null, … }`

Больше никакие критических комментариев нет, буду ждать финальную версию :)

2024-11-24 18:40 UTC, shooin13 commented on ImageFeedThird/Models/ProfileResult.swift
Блин, не подумал, использовал твою структуру для изменений, а тут lastname - не опционал

2024-11-24 18:42 UTC, shooin13 commented
@Kirchberg привет! Спасибо за ревью моего проекта.
Сорри, что затупил - не получалось сначала воспроизвести проблему (не думал о том что надо убрать приложение из трея).
ProfileResult - тоже понял, посмотрел какие поля при регистрации просят ввести, а там, действительно, last name - не обязательное.

2024-11-25 07:42 UTC, Kirchberg commented
Не забудь вмерджить пул-реквест в основную ветку.
Успехов в следующем задании ✨

2024-11-26 12:32 UTC, merged